### ISSUE TITLE
Cant run with regular user due to permission issue on /run/tor/control.authcookie

### ISSUE THREAD

**Issue by esmaeelE** [FujiwaraChoki/tor-demo#1]
```
(.venv) $ ls
LICENSE  README.md  requirements.txt  src
$ source .venv/bin/activate
(.venv) $ python3 src/main.py 
Round 1 of 3
Traceback (most recent call last):
  File "/home/esmaeel/develop/tor/tor-demo/.venv/lib/python3.11/site-packages/stem/connection.py", line 1103, in _read_cookie
    with open(cookie_path, 'rb', 0) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/run/tor/control.authcookie'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/esmaeel/develop/tor/tor-demo/src/main.py", line 72, in <module>
    renew_connection()
  File "/home/esmaeel/develop/tor/tor-demo/src/main.py", line 42, in renew_connection
    controller.authenticate(password="password")
  File "/home/esmaeel/develop/tor/tor-demo/.venv/lib/python3.11/site-packages/stem/control.py", line 1112, in authenticate
    stem.connection.authenticate(self, *args, **kwargs)
  File "/home/esmaeel/develop/tor/tor-demo/.venv/lib/python3.11/site-packages/stem/connection.py", line 629, in authenticate
    raise auth_exc
  File "/home/esmaeel/develop/tor/tor-demo/.venv/lib/python3.11/site-packages/stem/connection.py", line 591, in authenticate
    authenticate_safecookie(controller, cookie_path, False)
  File "/home/esmaeel/develop/tor/tor-demo/.venv/lib/python3.11/site-packages/stem/connection.py", line 904, in authenticate_safecookie
    cookie_data = _read_cookie(cookie_path, True)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/esmaeel/develop/tor/tor-demo/.venv/lib/python3.11/site-packages/stem/connection.py", line 1107, in _read_cookie
    raise UnreadableCookieFile(exc_msg, cookie_path, is_safecookie)
stem.connection.UnreadableCookieFile: Authentication failed: unable to read '/run/tor/control.authcookie' ([Errno 13] Permission denied: '/run/tor/control.authcookie')
(.venv) $ 
```

**Comment by FujiwaraChoki** [comment]
What are the perms? I would just give everyone access to it

**Comment by esmaeelE** [comment]
That is wrong work through even it solve the issue.

Changing a program internal files which is installed by package manager (for me `apt`) eventually will break package manager in futures.

Instead of apply obvious but wrong way we must solve it in correct way.
