### ISSUE TITLE
Runing under root user, using bridge error

### ISSUE THREAD

**Issue by esmaeelE** [FujiwaraChoki/tor-demo#2]
```
# python3 src/main.py 
Round 1 of 3
Circuit ID	Status	Path
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/esmaeel/develop/tor/tor-demo/.venv/lib/python3.11/site-packages/stem/control.py", line 2068, in get_network_status
    desc_content = self.get_info(query, get_bytes = True)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/esmaeel/develop/tor/tor-demo/.venv/lib/python3.11/site-packages/stem/control.py", line 489, in wrapped
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/esmaeel/develop/tor/tor-demo/.venv/lib/python3.11/site-packages/stem/control.py", line 1209, in get_info
    stem.response.convert('GETINFO', response)
  File "/home/esmaeel/develop/tor/tor-demo/.venv/lib/python3.11/site-packages/stem/response/__init__.py", line 124, in convert
    message._parse_message(**kwargs)
  File "/home/esmaeel/develop/tor/tor-demo/.venv/lib/python3.11/site-packages/stem/response/getinfo.py", line 44, in _parse_message
    raise stem.InvalidArguments('552', 'GETINFO request contained unrecognized keywords: %s\n' % ', '.join(unrecognized_keywords), unrecognized_keywords)
stem.InvalidArguments: GETINFO request contained unrecognized keywords: ns/name/bridge31
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/esmaeel/develop/tor/tor-demo/src/main.py", line 72, in <module>
    renew_connection()
  File "/home/esmaeel/develop/tor/tor-demo/src/main.py", line 48, in renew_connection
    print_circuit_info(controller)
  File "/home/esmaeel/develop/tor/tor-demo/src/main.py", line 28, in print_circuit_info
    path = ["".join(controller.get_network_status(entry[1]).address) for entry in circuit.path]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/esmaeel/develop/tor/tor-demo/src/main.py", line 28, in <listcomp>
    path = ["".join(controller.get_network_status(entry[1]).address) for entry in circuit.path]
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/esmaeel/develop/tor/tor-demo/.venv/lib/python3.11/site-packages/stem/control.py", line 489, in wrapped
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/esmaeel/develop/tor/tor-demo/.venv/lib/python3.11/site-packages/stem/control.py", line 2071, in get_network_status
    raise stem.DescriptorUnavailable("Tor was unable to provide the descriptor for '%s'" % relay)
stem.DescriptorUnavailable: Tor was unable to provide the descriptor for 'bridge31'
```

**Comment by FujiwaraChoki** [comment]
I was getting this error sometimes as well, reinstalling Tor fixed it for me.

**Comment by esmaeelE** [comment]
> I was getting this error sometimes as well, reinstalling Tor fixed it for me.

No, unfortunately its not work after reinstalling with `apt remove tor; apt install tor`

**Comment by FujiwaraChoki** [comment]
Sorry - then you might need to dig a bit deeper into stem.
